gsx_extrc:
- function: common
  params:
    mdl_cfg: mdlcfg
    memcache: False
- function: gen_sgn
  params:
    method: cd
    format: xml
    pval_thrshd: 0.1
    sample_dir: 
    ge_dir: 
    dge_dir: 

gsx_helper:
- function: common
  params:
    FUSEKI_ENV: 
    FUSEKI_PATH: 
    RAMSIZE: 4
    memcache: False

bionlp.spider.gsc:
- function: init
  params:
    DATA_PATH:
    GEO_PATH:
    ONTO_PATH:
    RXNAV_PATH:
    BIOGRID_PATH:
    HGNC_PATH:
    DNORM_PATH:

bionlp.spider.hgnc:
- function: init
  params:
    MAX_TRIAL:

bionlp.util.plot:
- function: init
  params:
    MON: False
- function: common
  params:
    save_obj: False
    save_npz: False
    notitle: False
    fmt: png
    style: 

bionlp.txtclf:
- function: cross_validate
  params:
    group_by_name: False
    save_crsval_idx: False
    save_crsval_pred: False
    save_perf_avg: True
    save_perf_avg_npz: False
    save_perf_std: False
    save_perf_std_npz: False
    save_povl: True
    save_povl_npz: False
    save_spmnr_avg: True
    save_spmnr_avg_npz: False
    save_spmnr_pval: False
    save_spmnr_pval_npz: False
    save_featw: False
    save_featw_npz: False
    save_subfeatw: False
    save_subfeatw_npz: False
    save_auc: True
    plot_featw: False
    plot_subfeatw: False
    plot_roc: True
    plot_prc: True
    plot_metric: False
- function: classification
  params:
    save_pred: True
    save_povl: True
    save_povl_npz: False
    save_spmnr: True
    save_spmnr_npz: False
    save_spmnr_pval: False
    save_spmnr_pval_npz: False
    save_featw: False
    save_featw_npz: False
    save_subfeatw: False
    save_subfeatw_npz: False

bionlp.txtclt:
- function: cross_validate
  params:
    save_crsval_idx: False
    save_crsval_pred: False
    save_perf_avg: True
    save_perf_avg_npz: False
    save_perf_std: False
    save_perf_std_npz: False
    save_povl: True
    save_povl_npz: False
    save_spmnr_avg: True
    save_spmnr_avg_npz: False
    save_spmnr_pval: False
    save_spmnr_pval_npz: False
    save_featw: False
    save_featw_npz: False
    save_subfeatw: False
    save_subfeatw_npz: False
    save_auc: True
    plot_featw: False
    plot_subfeatw: False
    plot_roc: True
    plot_prc: True
    plot_metric: False
- function: clustering
  params:
    save_pred: True
    save_povl: True
    save_povl_npz: False
    save_spmnr: True
    save_spmnr_npz: False
    save_spmnr_pval: False
    save_spmnr_pval_npz: False