Feature Selection:
- name: Logistic Regression
  params:
    C: 1000.0
    penalty: l1
    tol: 1.0e-06

Classifier:
- name: Logistic Regression
  params:
    C: 10.0
    penalty: l2
    tol: 1.0e-01
- name: MultinomialNB
  params:
    alpha: 0.001
    fit_prior: true
- name: kNN
  params:
    algorithm: auto
- name: Perceptron
  params:
    alpha: 0.001
    n_iter: 3
- name: SVM
  params:
    C: 1.0
    gamma: 100.0
    kernel: linear
- name: RBF SVM
  params:
    C: 1000.0
    gamma: 1.0e-05
    kernel: rbf
- name: LinearSVC
  params:
    C: 1.0
    penalty: l1
    tol: 0.1
- name: Extra Trees
  params:
    max_features: 0.7
    min_samples_leaf: 20
    n_estimators: 500
## GSE RF ##
- name: Random Forest GSE
  params:
    max_features: 0.6
    min_samples_leaf: 1
    max_depth: 40
    n_estimators: 200
    class_weight: balanced
## GSM RF 0 ##
- name: Random Forest GSM0
  params:
    max_features: 0.8
    min_samples_leaf: 100
    max_depth: 10
    n_estimators: 600
    class_weight: balanced
## GSM RF 1 ##
- name: Random Forest GSM1
  params:
    max_features: 0.8
    min_samples_leaf: 70
    max_depth: 90
    n_estimators: 500
    class_weight: None
## GSM RF 2 ##
- name: Random Forest GSM2
  params:
    max_features: 0.5
    min_samples_leaf: 40
    max_depth: 50
    n_estimators: 500
    class_weight: None
- name: GBoost
  params:
    learning_rate: 0.95
    loss: deviance
    max_features: 0.8
    min_samples_leaf: 100
    max_depth: 95
    n_estimators: 315
    subsample: 0.6
    warm_start: false